name: Rust

on:
  push:
    branches:
      - main
      - '0\.*\.*'
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy
        override: true

    - name: Repl
      run: |
        make repl

    - name: Repl of Origin
      run: |
        make repl_origin

    - name: Test
      run: make test

    - name: Example
      run: |
        make example